export const DB_META = {
  mssql:      {label:'MS',bg:'#e6f1fb',color:'#185fa5',port:1433, versions:['SQL Server 2022','SQL Server 2019','SQL Server 2017','SQL Server 2016']},
  oracle:     {label:'Or',bg:'#fff0eb',color:'#993c1d',port:1521, versions:['Oracle 21c','Oracle 19c','Oracle 12c','Oracle 11g']},
  postgresql: {label:'PG',bg:'#e6f1fb',color:'#185fa5',port:5432, versions:['PostgreSQL 16','PostgreSQL 15','PostgreSQL 14','PostgreSQL 13']},
  mysql:      {label:'My',bg:'#eaf3de',color:'#3b6d11',port:3306, versions:['MySQL 8.0','MySQL 5.7','MariaDB 10.11','MariaDB 10.6']},
  db2:        {label:'DB',bg:'#eeedfe',color:'#534ab7',port:50000,versions:['DB2 12','DB2 11.5','DB2 10.5']},
  hana:       {label:'HA',bg:'#faeeda',color:'#854f0b',port:30015,versions:['HANA 2.0 SPS07','HANA 2.0 SPS06']},
  sybase:     {label:'Sy',bg:'#faece7',color:'#993c1d',port:5000, versions:['ASE 16','ASE 15.7']},
  sqlite:     {label:'SL',bg:'#f1efe8',color:'#5f5e5a',port:null, versions:['SQLite 3.x']},
  mongodb:    {label:'Mo',bg:'#eaf3de',color:'#3b6d11',port:27017,versions:['MongoDB 7','MongoDB 6','MongoDB 5']},
  redshift:   {label:'RS',bg:'#e6f1fb',color:'#185fa5',port:5439, versions:['Redshift (최신)']},
  teradata:   {label:'Td',bg:'#eeedfe',color:'#534ab7',port:1025, versions:['Teradata 17','Teradata 16']},
  aurora:     {label:'Au',bg:'#eaf3de',color:'#3b6d11',port:3306, versions:['Aurora MySQL 3','Aurora MySQL 2','Aurora PostgreSQL 15']},
  cloudsql:   {label:'GC',bg:'#faeeda',color:'#854f0b',port:3306, versions:['Cloud SQL MySQL 8','Cloud SQL PG 15']},
  azure:      {label:'Az',bg:'#e6f1fb',color:'#185fa5',port:1433, versions:['Azure SQL 2022','Azure SQL 2019']},
  snowflake:  {label:'SF',bg:'#faece7',color:'#993c1d',port:443,  versions:['Snowflake (최신)']},
  clickhouse: {label:'CH',bg:'#faeeda',color:'#854f0b',port:8123, versions:['ClickHouse 23','ClickHouse 22']},
  tidb:       {label:'Ti',bg:'#eeedfe',color:'#534ab7',port:4000, versions:['TiDB 7','CockroachDB 23']},
  bigquery:   {label:'BQ',bg:'#eaf3de',color:'#3b6d11',port:443,  versions:['BigQuery (최신)']},
  duckdb:     {label:'DK',bg:'#f1efe8',color:'#5f5e5a',port:null, versions:['DuckDB 0.9','DuckDB 0.8']},
}

export const SOURCE_DBS = [
  {value:'mssql',name:'Microsoft SQL Server'},
  {value:'oracle',name:'Oracle Database'},
  {value:'postgresql',name:'PostgreSQL'},
  {value:'mysql',name:'MySQL / MariaDB'},
  {value:'db2',name:'IBM DB2'},
  {value:'hana',name:'SAP HANA'},
  {value:'sybase',name:'Sybase / ASE'},
  {value:'sqlite',name:'SQLite'},
  {value:'mongodb',name:'MongoDB'},
  {value:'redshift',name:'Amazon Redshift'},
  {value:'teradata',name:'Teradata'},
]

export const TARGET_DBS = [
  {value:'mysql',name:'MySQL / MariaDB'},
  {value:'postgresql',name:'PostgreSQL'},
  {value:'oracle',name:'Oracle Database'},
  {value:'mssql',name:'Microsoft SQL Server'},
  {value:'aurora',name:'Amazon Aurora'},
  {value:'cloudsql',name:'Google Cloud SQL'},
  {value:'azure',name:'Azure SQL Database'},
  {value:'snowflake',name:'Snowflake'},
  {value:'clickhouse',name:'ClickHouse'},
  {value:'tidb',name:'TiDB / CockroachDB'},
  {value:'bigquery',name:'Google BigQuery'},
  {value:'duckdb',name:'DuckDB'},
]
